BEGIN;

CREATE TABLE IF NOT EXISTS lead_domains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT lead_domains_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS domain_courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain_id BIGINT NOT NULL REFERENCES lead_domains(id) ON DELETE CASCADE,
  name VARCHAR(200) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT domain_courses_name_key UNIQUE (domain_id, name)
);

CREATE TABLE IF NOT EXISTS counsellor_routing_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  domain_id BIGINT NOT NULL REFERENCES lead_domains(id) ON DELETE CASCADE,
  course_id BIGINT REFERENCES domain_courses(id) ON DELETE CASCADE,
  auto_assign BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_assigned_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT counsellor_routing_assignments_unique UNIQUE NULLS NOT DISTINCT (employee_id, domain_id, course_id)
);

ALTER TABLE leads ADD COLUMN IF NOT EXISTS domain VARCHAR(150);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assignment_mode VARCHAR(20) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS routing_rule_description TEXT;

ALTER TABLE leads DROP CONSTRAINT IF EXISTS leads_assignment_mode_check;
ALTER TABLE leads ADD CONSTRAINT leads_assignment_mode_check CHECK (assignment_mode IN ('MANUAL', 'AUTO'));

CREATE INDEX IF NOT EXISTS idx_domain_courses_domain_id ON domain_courses(domain_id) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_counsellor_routing_lookup ON counsellor_routing_assignments(domain_id, course_id, last_assigned_at) WHERE is_active = TRUE AND auto_assign = TRUE;

INSERT INTO lead_domains (name) VALUES
  ('DizitalAdda'),
  ('Nidads'),
  ('Nigape'),
  ('Nihacs'),
  ('HackingVidya'),
  ('IIDAD'),
  ('Nifase'),
  ('DesigningVidya'),
  ('LanguageVidya')
ON CONFLICT (name) DO NOTHING;

COMMIT;
