-- Migration: Add lead_feedback table for structured status feedback tracking
BEGIN;

CREATE TABLE IF NOT EXISTS lead_feedback (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id             BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    status_at_feedback  VARCHAR(50) NOT NULL,
    feedback_fields     JSONB NOT NULL DEFAULT '{}'::jsonb,
    remarks             TEXT,
    created_by          BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_lead_feedback_lead_id ON lead_feedback (lead_id, created_at DESC);

COMMIT;
